#pragma once

#include <CurlX/Auth.hpp>
#include <CurlX/Body.hpp>
#include <CurlX/Client.hpp>
#include <CurlX/Cookies.hpp>
#include <CurlX/Delete.hpp>
#include <CurlX/Exceptions.hpp>
#include <CurlX/Files.hpp>
#include <CurlX/Get.hpp>
#include <CurlX/Head.hpp>
#include <CurlX/HeaderOutputStream.hpp>
#include <CurlX/Headers.hpp>
#include <CurlX/Method.hpp>
#include <CurlX/Options.hpp>
#include <CurlX/Params.hpp>
#include <CurlX/Patch.hpp>
#include <CurlX/Post.hpp>
#include <CurlX/Proxy.hpp>
#include <CurlX/Put.hpp>
#include <CurlX/Redirects.hpp>
#include <CurlX/Request.hpp>
#include <CurlX/Response.hpp>
#include <CurlX/Session.hpp>
#include <CurlX/Timeout.hpp>
#include <CurlX/Url.hpp>
#include <CurlX/Verify.hpp>